name: 'Code Review GPT'
description: 'Reviews PR changes with a GPT model from OpenAI'
author: 'Orion Tools'
inputs:
  MODEL:
    description: 'Model name to use for review'
    required: true
    default: 'gpt-4o'
  REVIEW_LANGUAGE:
    description: 'Target natural language for translation'
    required: false
    default: 'English'
  OPENAI_API_KEY:
    description: 'OpenAI API Key'
    required: true
  GITHUB_TOKEN:
    description: 'Github token'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install Code Review GPT
      shell: bash
      run: bun i
    
    - name: Run Code Review GPT
      shell: bash
      run: bun code-review-gpt review --ci=github --model=$MODEL --reviewLanguage=$REVIEW_LANGUAGE
      
      env:
        MODEL: ${{ inputs.MODEL }}
        REVIEW_LANGUAGE: ${{ inputs.REVIEW_LANGUAGE }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

branding:
  icon: 'code'
  color: 'blue'