name: "Shippie 🚢"
description: "an extensible code review agent"
author: "Matt Carey"
inputs:
  MODEL_STRING:
    description: "Model name to use for review"
    required: false
    default: "openai:gpt-4.1-mini"
  REVIEW_LANGUAGE:
    description: "Target natural language for translation"
    required: false
    default: "English"
  OPENAI_API_KEY:
    description: "OpenAI API Key"
    required: false
  GOOGLE_GENERATIVE_AI_API_KEY:
    description: "Google API Key"
    required: false
  ANTHROPIC_API_KEY:
    description: "Anthropic API Key"
    required: false
  GITHUB_TOKEN:
    description: "Github token"
    required: true
  BASE_URL:
    description: "AI Provider Base URL"
    required: false
  MAX_STEPS:
    description: "Maximum number of agentic steps to take"
    required: false
    default: "25"
  TELEMETRY:
    description: "Enables anonymous telemetry"
    required: false
    default: "true"
  DEBUG:
    description: "Enables debug logging"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install and Run Shippie 🚢
      shell: bash
      run: |
        bun install --frozen-lockfile
        bun review --debug=$DEBUG --platform=github --modelString=$MODEL_STRING --reviewLanguage=$REVIEW_LANGUAGE --maxSteps=$MAX_STEPS --baseUrl=$BASE_URL --telemetry=$TELEMETRY
      env:
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY || env.OPENAI_API_KEY }}
        GOOGLE_GENERATIVE_AI_API_KEY: ${{ inputs.GOOGLE_GENERATIVE_AI_API_KEY || env.GOOGLE_GENERATIVE_AI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ inputs.ANTHROPIC_API_KEY || env.ANTHROPIC_API_KEY }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN || env.GITHUB_TOKEN }}
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        GITHUB_SHA: ${{ github.sha }}
branding:
  icon: "git-pull-request"
  color: "red"
